name: Example First deploy
on:
  push:
    branches:
      - master
jobs:
  first_job:
    
    runs-on: ubuntu-latest
    env:
      NAME: Benjamin
    
    steps:
      - name: Hola Mundo
      - run: echo "Hola $NAME"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo2
      - run: echo "Hola Mundo2"
 