name: Example First deploy
on:
  push:
    branches:
      - master
jobs:
  first_job:
    
    runs-on: ubuntu-latest
    env:
      NAME: Benjamin
    
    steps:
      - name: Hola Mundo
      - run: echo "Hola $NAME"
 