name: First Jobs deploy example
on:
  push:
    branches:
      - master
jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: VAR1
    
    steps:
      - name: Hola Mundo
      - run: echo "Hola Mundo"
  second_job:
    if: ${{ gitHub.refs == 'refs/heads/master' }}
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo2
      - run: echo "Hola Mundo $"
 