name: Example First deploy
on:
  push:
    branches:
      - master
jobs:
  first_job:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: [hello, world, benjamin]
    
    steps:
      - name: Print msj
        run: |
          echo ${{ matrix.message }}
