name: Example First deploy
on:
  push:
    branches:
      - master
jobs:
  first_job:
    
    runs-on: ubuntu-latest
    env:
      NAME: Benjamin
    
    steps:
      - name: Hola Mundo
        run: echo "Hola $NAME"

      - name: Working dir
        id: step1
        run: echo "my_variable=HolaMundo" >> $GITHUB_OUTPUT

      - name: Obtener msj
        run: echo "Hola ${{ steps.step1.outputs.my_variable }}"
      
      - name: Actions
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola ${{ github.ref }}"