name: Example First deploy
on:
  push:
    branches:
      - master
jobs:
  first_job:
    
    runs-on: ubuntu-latest
    env:
      NAME: Benjamin
    
    outputs: 
      my_variable: HolaMundo

    steps:
      - name: Hola Mundo
        run: echo "Hola $NAME"

      - name: Working dir
        id: step1
        run: echo "my_variable=HolaMundo" >> $GITHUB_OUTPUT

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola ${{ github.ref }}"

      - name: Obtener msj de la variable
        run: echo "Hola ${{ needs.first_job.outputs.my_variable }}"